"""Pruebas del empaquetador del artefacto de Lambda (`Task/024`).

Cubren la **logica pura** de `scripts/empaquetar_lambda.py`: inventario del
lock, contraste con el arbol instalado, normalizacion, politica de contenido,
politica de binarios, determinismo del ZIP, gates de tamano y manifiesto.

Lo que **no** esta aqui, y por que
----------------------------------

Los casos de capa *artefacto* de la matriz de la ficha —construccion real,
reproducibilidad `A == B`, ejecucion aislada del *handler*, cargas nativas y
controles negativos de aislamiento— exigen Docker, la imagen del runtime fijada
por digest y varios minutos de descarga. Viven en los subcomandos de la propia
herramienta y en `CI Backend`, no en esta suite: meterlos aqui la volveria lenta
y dependiente de Docker sin ganar rigor.

Ningun test de este modulo toca la red, Docker ni el sistema de archivos fuera
de `tmp_path`.
"""

from __future__ import annotations

import os
import re
import stat
import zipfile
from pathlib import Path

import pytest

from scripts.empaquetar_lambda import (
    NOMBRE_DEL_ARTEFACTO,
    ErrorDeEmpaquetado,
    comando_de_instalacion,
    construir_manifiesto,
    distribuciones_del_lock,
    distribuciones_instaladas,
    escribir_zip,
    medir,
    normalizar_arbol,
    recolectar_entradas,
    sha256_de,
    verificar_binarios,
    verificar_contenido,
    verificar_inventario,
    verificar_layout,
    verificar_rutas,
    verificar_tamano,
)

# ---------------------------------------------------------------------------
# Utilidades de construccion de arboles sinteticos
# ---------------------------------------------------------------------------

#: Lock minimo con la forma exacta que genera `uv pip compile --generate-hashes`.
LOCK_DE_EJEMPLO = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile pyproject.toml --generate-hashes
fastapi==0.141.1 \\
    --hash=sha256:1111111111111111111111111111111111111111111111111111111111111111
    # via personal-blog-backend (pyproject.toml)
mangum==0.22.0 \\
    --hash=sha256:2222222222222222222222222222222222222222222222222222222222222222 \\
    --hash=sha256:3333333333333333333333333333333333333333333333333333333333333333
    # via personal-blog-backend (pyproject.toml)
argon2-cffi==25.1.0 \\
    --hash=sha256:4444444444444444444444444444444444444444444444444444444444444444
    # via personal-blog-backend (pyproject.toml)
"""

#: Cabecera ELF de 64 bits, little endian. `e_machine` vive en el offset 18.
_ELF_X86_64 = 62
_ELF_AARCH64 = 183


def _elf(maquina: int) -> bytes:
    """Construye una cabecera ELF64 valida con la arquitectura indicada."""
    cabecera = bytearray(64)
    cabecera[0:4] = b"\x7fELF"
    cabecera[4] = 2  # ELFCLASS64
    cabecera[5] = 1  # ELFDATA2LSB
    cabecera[6] = 1  # EV_CURRENT
    cabecera[16:18] = (3).to_bytes(2, "little")  # ET_DYN
    cabecera[18:20] = maquina.to_bytes(2, "little")
    return bytes(cabecera)


def _escribir(raiz: Path, ruta: str, contenido: bytes = b"contenido\n") -> Path:
    """Crea `ruta` bajo `raiz` con los directorios intermedios necesarios."""
    destino = raiz / ruta
    destino.parent.mkdir(parents=True, exist_ok=True)
    destino.write_bytes(contenido)
    return destino


def _arbol_valido(raiz: Path) -> Path:
    """Arbol minimo que satisface el *layout* y el inventario de ejemplo."""
    _escribir(raiz, "app/__init__.py")
    _escribir(raiz, "app/main.py")
    _escribir(raiz, "app/lambda_handler.py")
    _escribir(raiz, "fastapi/__init__.py")
    _escribir(raiz, "fastapi-0.141.1.dist-info/METADATA")
    _escribir(raiz, "mangum/__init__.py")
    _escribir(raiz, "mangum-0.22.0.dist-info/METADATA")
    _escribir(raiz, "argon2/__init__.py")
    _escribir(raiz, "argon2_cffi-25.1.0.dist-info/METADATA")
    return raiz


def _rutas(raiz: Path) -> list[str]:
    return [entrada.ruta for entrada in recolectar_entradas(raiz)]


# ---------------------------------------------------------------------------
# A — Layout y handler
# ---------------------------------------------------------------------------


def test_el_layout_valido_se_acepta(tmp_path: Path) -> None:
    """A1: `app/` en la raiz con el *handler* presente."""
    verificar_layout(_rutas(_arbol_valido(tmp_path)))


def test_el_layout_sin_handler_se_rechaza(tmp_path: Path) -> None:
    """A2: falta `app/lambda_handler.py`."""
    _arbol_valido(tmp_path)
    (tmp_path / "app" / "lambda_handler.py").unlink()

    with pytest.raises(ErrorDeEmpaquetado, match=re.escape("app/lambda_handler.py")):
        verificar_layout(_rutas(tmp_path))


def test_el_layout_anidado_se_rechaza(tmp_path: Path) -> None:
    """A3: el arbol cuelga de `lambda_package/`, no de la raiz."""
    _arbol_valido(tmp_path / "lambda_package")

    with pytest.raises(ErrorDeEmpaquetado, match="lambda_package"):
        verificar_layout(_rutas(tmp_path))


def test_el_prefijo_de_layer_se_rechaza(tmp_path: Path) -> None:
    """A4: `python/` es el prefijo de las *layers*, y aqui no se crean layers."""
    _arbol_valido(tmp_path / "python")

    with pytest.raises(ErrorDeEmpaquetado, match="python/"):
        verificar_layout(_rutas(tmp_path))


# ---------------------------------------------------------------------------
# B, C, D — Inventario frente al lock
# ---------------------------------------------------------------------------


def test_el_lock_de_ejemplo_se_lee_completo() -> None:
    """El parser devuelve nombre normalizado y version de cada distribucion."""
    assert distribuciones_del_lock(LOCK_DE_EJEMPLO) == {
        "fastapi": "0.141.1",
        "mangum": "0.22.0",
        "argon2-cffi": "25.1.0",
    }


def test_el_lock_real_trae_las_distribuciones_de_ejecucion() -> None:
    """El lock de ejecucion del repositorio es la fuente del artefacto."""
    lock = Path("requirements.lock").read_text(encoding="utf-8")
    distribuciones = distribuciones_del_lock(lock)

    assert len(distribuciones) == 41
    assert distribuciones["mangum"] == "0.22.0"
    assert "pytest" not in distribuciones
    assert "ruff" not in distribuciones
    assert "mypy" not in distribuciones


def test_un_lock_sin_hashes_se_rechaza() -> None:
    """D1: un lock sin `--hash` no es *fail-closed* y no puede usarse."""
    with pytest.raises(ErrorDeEmpaquetado, match="hash"):
        distribuciones_del_lock("fastapi==0.141.1\n")


def test_una_distribucion_faltante_se_rechaza(tmp_path: Path) -> None:
    """B1: el arbol no trae `mangum`."""
    _arbol_valido(tmp_path)
    (tmp_path / "mangum-0.22.0.dist-info" / "METADATA").unlink()
    (tmp_path / "mangum-0.22.0.dist-info").rmdir()

    with pytest.raises(ErrorDeEmpaquetado, match="mangum"):
        verificar_inventario(
            esperadas=distribuciones_del_lock(LOCK_DE_EJEMPLO),
            instaladas=distribuciones_instaladas(tmp_path),
        )


def test_el_inventario_completo_se_acepta(tmp_path: Path) -> None:
    """B2: estan las tres del lock de ejemplo y ninguna mas."""
    verificar_inventario(
        esperadas=distribuciones_del_lock(LOCK_DE_EJEMPLO),
        instaladas=distribuciones_instaladas(_arbol_valido(tmp_path)),
    )


def test_una_distribucion_extra_se_rechaza(tmp_path: Path) -> None:
    """C1 y N1: una dependencia de desarrollo no puede viajar al artefacto."""
    _arbol_valido(tmp_path)
    _escribir(tmp_path, "pytest-9.1.1.dist-info/METADATA")

    with pytest.raises(ErrorDeEmpaquetado, match="pytest"):
        verificar_inventario(
            esperadas=distribuciones_del_lock(LOCK_DE_EJEMPLO),
            instaladas=distribuciones_instaladas(tmp_path),
        )


def test_una_version_distinta_se_rechaza(tmp_path: Path) -> None:
    """C2: la version instalada no es la que fija el lock."""
    _arbol_valido(tmp_path)
    (tmp_path / "fastapi-0.141.1.dist-info").rename(tmp_path / "fastapi-0.140.0.dist-info")

    with pytest.raises(ErrorDeEmpaquetado, match=re.escape("0.140.0")):
        verificar_inventario(
            esperadas=distribuciones_del_lock(LOCK_DE_EJEMPLO),
            instaladas=distribuciones_instaladas(tmp_path),
        )


def test_el_comando_de_instalacion_es_fail_closed() -> None:
    """D2: los tres interruptores que impiden un artefacto no reproducible."""
    comando = comando_de_instalacion(lock="/src/requirements.lock", destino="/build/arbol")

    assert "--require-hashes" in comando
    assert "--only-binary=:all:" in comando
    assert "--no-compile" in comando
    assert "/src/requirements.lock" in comando
    assert "/build/arbol" in comando


# ---------------------------------------------------------------------------
# E, F — Binarios
# ---------------------------------------------------------------------------


def test_un_binario_de_windows_se_rechaza(tmp_path: Path) -> None:
    """E1: un PE/COFF de Windows no arranca en el runtime de Lambda."""
    _arbol_valido(tmp_path)
    _escribir(tmp_path, "argon2/_ffi.pyd", b"MZ\x90\x00" + bytes(60))

    with pytest.raises(ErrorDeEmpaquetado, match=re.escape("argon2/_ffi.pyd")):
        verificar_binarios(recolectar_entradas(tmp_path))


def test_un_elf_de_otra_arquitectura_se_rechaza(tmp_path: Path) -> None:
    """F1: un objeto AArch64 en un artefacto x86-64."""
    _arbol_valido(tmp_path)
    _escribir(tmp_path, "argon2/_ffi.abi3.so", _elf(_ELF_AARCH64))

    with pytest.raises(ErrorDeEmpaquetado, match=re.escape("argon2/_ffi.abi3.so")):
        verificar_binarios(recolectar_entradas(tmp_path))


def test_un_elf_x86_64_se_acepta(tmp_path: Path) -> None:
    """F2: la arquitectura correcta pasa el gate."""
    _arbol_valido(tmp_path)
    _escribir(tmp_path, "argon2/_ffi.abi3.so", _elf(_ELF_X86_64))

    verificar_binarios(recolectar_entradas(tmp_path))


# ---------------------------------------------------------------------------
# G, H, I — Determinismo del ZIP
# ---------------------------------------------------------------------------


def test_los_timestamps_del_arbol_no_afectan_al_zip(tmp_path: Path) -> None:
    """G1: dos arboles identicos con `mtime` distintos dan el mismo ZIP."""
    primero = _arbol_valido(tmp_path / "primero")
    segundo = _arbol_valido(tmp_path / "segundo")
    for ruta in sorted(segundo.rglob("*")):
        if ruta.is_file():
            os.utime(ruta, (1_000_000_000, 1_000_000_000))

    zip_a = tmp_path / "a.zip"
    zip_b = tmp_path / "b.zip"
    escribir_zip(recolectar_entradas(primero), zip_a)
    escribir_zip(recolectar_entradas(segundo), zip_b)

    assert zip_a.read_bytes() == zip_b.read_bytes()


def test_las_entradas_van_en_orden_lexicografico(tmp_path: Path) -> None:
    """G2: el orden de entrega no altera el orden dentro del ZIP."""
    raiz = _arbol_valido(tmp_path / "arbol")
    entradas = recolectar_entradas(raiz)
    destino = tmp_path / "a.zip"

    escribir_zip(reversed(entradas), destino)

    with zipfile.ZipFile(destino) as archivo:
        assert archivo.namelist() == sorted(entrada.ruta for entrada in entradas)


def test_los_permisos_y_la_fecha_se_normalizan(tmp_path: Path) -> None:
    """G3 y C-024: modo `0644`, sistema Unix, fecha minima del formato ZIP."""
    raiz = _arbol_valido(tmp_path / "arbol")
    destino = tmp_path / "a.zip"

    escribir_zip(recolectar_entradas(raiz), destino)

    with zipfile.ZipFile(destino) as archivo:
        assert archivo.comment == b""
        for info in archivo.infolist():
            assert info.date_time == (1980, 1, 1, 0, 0, 0)
            assert info.create_system == 3
            assert stat.S_IMODE(info.external_attr >> 16) == 0o644
            assert info.compress_type == zipfile.ZIP_DEFLATED


def test_dos_arboles_equivalentes_producen_el_mismo_zip(tmp_path: Path) -> None:
    """H1: mismo contenido en directorios distintos, mismos bytes y mismo SHA."""
    zip_a = tmp_path / "a.zip"
    zip_b = tmp_path / "b.zip"
    escribir_zip(recolectar_entradas(_arbol_valido(tmp_path / "A")), zip_a)
    escribir_zip(recolectar_entradas(_arbol_valido(tmp_path / "B")), zip_b)

    assert zip_a.read_bytes() == zip_b.read_bytes()
    assert sha256_de(zip_a) == sha256_de(zip_b)


def test_un_cambio_real_cambia_el_checksum(tmp_path: Path) -> None:
    """I1: un byte distinto produce otro SHA-256."""
    primero = _arbol_valido(tmp_path / "A")
    segundo = _arbol_valido(tmp_path / "B")
    (segundo / "app" / "main.py").write_bytes(b"contenido distinto\n")

    zip_a = tmp_path / "a.zip"
    zip_b = tmp_path / "b.zip"
    escribir_zip(recolectar_entradas(primero), zip_a)
    escribir_zip(recolectar_entradas(segundo), zip_b)

    assert sha256_de(zip_a) != sha256_de(zip_b)


# ---------------------------------------------------------------------------
# J — Gates de tamano
# ---------------------------------------------------------------------------


def test_el_gate_de_tamano_acepta_debajo_y_en_el_umbral(tmp_path: Path) -> None:
    """J1 y J2: la cuota de Lambda es inclusiva."""
    raiz = _arbol_valido(tmp_path / "arbol")
    destino = tmp_path / "a.zip"
    escribir_zip(recolectar_entradas(raiz), destino)
    medida = medir(recolectar_entradas(raiz), destino)

    verificar_tamano(medida)
    verificar_tamano(
        medida.reemplazando(
            bytes_comprimidos=52_428_800,
            bytes_descomprimidos=262_144_000,
        )
    )


def test_el_gate_de_tamano_rechaza_por_encima(tmp_path: Path) -> None:
    """J3: un byte por encima de cualquiera de las dos cuotas falla."""
    raiz = _arbol_valido(tmp_path / "arbol")
    destino = tmp_path / "a.zip"
    escribir_zip(recolectar_entradas(raiz), destino)
    medida = medir(recolectar_entradas(raiz), destino)

    with pytest.raises(ErrorDeEmpaquetado, match="comprimido"):
        verificar_tamano(medida.reemplazando(bytes_comprimidos=52_428_801))

    with pytest.raises(ErrorDeEmpaquetado, match="descomprimido"):
        verificar_tamano(medida.reemplazando(bytes_descomprimidos=262_144_001))


def test_la_medida_desglosa_por_distribucion(tmp_path: Path) -> None:
    """El desglose por distribucion es el dato que `P-07` necesita."""
    raiz = _arbol_valido(tmp_path / "arbol")
    destino = tmp_path / "a.zip"
    entradas = recolectar_entradas(raiz)
    escribir_zip(entradas, destino)

    medida = medir(entradas, destino)

    assert medida.archivos == len(entradas)
    assert medida.bytes_comprimidos == destino.stat().st_size
    assert medida.por_distribucion["app"] > 0
    assert medida.por_distribucion["mangum"] > 0
    assert sum(medida.por_distribucion.values()) == medida.bytes_descomprimidos


# ---------------------------------------------------------------------------
# K, L, M, N, O — Contenido prohibido
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "ruta",
    [
        pytest.param(".env", id="K1-env-en-la-raiz"),
        pytest.param("app/.env", id="K2-env-anidado"),
        pytest.param(".env.example", id="K1-env-example"),
        pytest.param("credentials.json", id="L1-credenciales"),
        pytest.param("app/id_rsa", id="L1-clave-privada"),
        pytest.param("certificado.pem", id="L1-pem"),
        pytest.param(".git/config", id="L2-control-de-versiones"),
        pytest.param("tests/unit/test_x.py", id="M1-pruebas"),
        pytest.param("scripts/seed_local.py", id="M2-utilidades"),
        pytest.param("app/main.pyc", id="O2-bytecode-suelto"),
        pytest.param("app/__pycache__/main.cpython-312.pyc", id="O1-pycache"),
        pytest.param(".pytest_cache/CACHEDIR.TAG", id="O3-cache-de-pytest"),
        pytest.param(".ruff_cache/0.16.1/x", id="O3-cache-de-ruff"),
        pytest.param(".venv/pyvenv.cfg", id="entorno-virtual"),
    ],
)
def test_el_contenido_prohibido_se_rechaza(ruta: str) -> None:
    """K, L, M, N, O: nada de esto puede viajar dentro del artefacto."""
    with pytest.raises(ErrorDeEmpaquetado, match="prohibido"):
        verificar_contenido(["app/lambda_handler.py", ruta])


def test_el_contenido_legitimo_se_acepta() -> None:
    """El gate no puede rechazar lo que una distribucion si necesita."""
    verificar_contenido(
        [
            "app/lambda_handler.py",
            "argon2/_ffi.abi3.so",
            "pillow.libs/libjpeg-abcdef.so.62.4.0",
            "fastapi-0.141.1.dist-info/licenses/LICENSE",
            "fastapi-0.141.1.dist-info/RECORD",
            "mako/templates.py",
            "psycopg_binary/pq/pq_cython.pyi",
        ]
    )


def test_el_bytecode_y_las_caches_se_eliminan_en_la_normalizacion(tmp_path: Path) -> None:
    """O1 y O3: la normalizacion los borra antes de recolectar entradas."""
    raiz = _arbol_valido(tmp_path)
    _escribir(raiz, "app/__pycache__/main.cpython-312.pyc")
    _escribir(raiz, "fastapi/__pycache__/x.cpython-312.pyc")
    _escribir(raiz, ".pytest_cache/CACHEDIR.TAG")
    _escribir(raiz, ".ruff_cache/0.16.1/x")
    _escribir(raiz, "app/suelto.pyc")

    eliminados = normalizar_arbol(raiz)

    assert eliminados
    verificar_contenido(_rutas(raiz))
    assert not list(raiz.rglob("*.pyc"))
    assert not list(raiz.rglob("__pycache__"))


# ---------------------------------------------------------------------------
# P, Q, R, S — Rutas y enlaces
# ---------------------------------------------------------------------------


def test_una_ruta_con_traversal_se_rechaza() -> None:
    """P1: una entrada que escapa del arbol al extraerse."""
    with pytest.raises(ErrorDeEmpaquetado, match=r"\.\."):
        verificar_rutas(["app/lambda_handler.py", "../fuera.py"])


@pytest.mark.parametrize(
    "ruta",
    [
        pytest.param("/etc/passwd", id="posix"),
        pytest.param("C:/Users/x", id="windows-con-barra"),
        pytest.param("C:\\Users\\x", id="windows-con-contrabarra"),
    ],
)
def test_una_ruta_absoluta_se_rechaza(ruta: str) -> None:
    """Q1: el ZIP no puede llevar rutas absolutas."""
    with pytest.raises(ErrorDeEmpaquetado, match="absoluta"):
        verificar_rutas(["app/lambda_handler.py", ruta])


def test_una_entrada_duplicada_se_rechaza() -> None:
    """R1: dos entradas con la misma ruta hacen ambiguo el artefacto."""
    with pytest.raises(ErrorDeEmpaquetado, match="duplicada"):
        verificar_rutas(["app/main.py", "app/main.py"])


def test_las_rutas_legitimas_se_aceptan() -> None:
    """El gate de rutas no puede rechazar una ruta POSIX relativa normal."""
    verificar_rutas(["app/lambda_handler.py", "pillow.libs/libjpeg-abcdef.so.62.4.0"])


def test_un_enlace_simbolico_se_rechaza(tmp_path: Path) -> None:
    """S1: la politica los prohibe; un enlace dentro de un ZIP es ambiguo."""
    raiz = _arbol_valido(tmp_path)
    try:
        (raiz / "atajo.py").symlink_to(raiz / "app" / "main.py")
    except OSError as error:  # pragma: no cover - depende de los permisos del SO
        pytest.skip(f"el sistema operativo no permite crear enlaces simbolicos: {error}")

    with pytest.raises(ErrorDeEmpaquetado, match="enlace simbolico"):
        recolectar_entradas(raiz)


# ---------------------------------------------------------------------------
# Manifiesto y checksum
# ---------------------------------------------------------------------------


def test_el_manifiesto_registra_la_procedencia(tmp_path: Path) -> None:
    """El manifiesto debe bastar para saber de donde salio el artefacto."""
    raiz = _arbol_valido(tmp_path / "arbol")
    destino = tmp_path / "a.zip"
    entradas = recolectar_entradas(raiz)
    escribir_zip(entradas, destino)

    manifiesto = construir_manifiesto(
        entradas=entradas,
        artefacto=destino,
        medida=medir(entradas, destino),
        distribuciones=distribuciones_del_lock(LOCK_DE_EJEMPLO),
        lock=LOCK_DE_EJEMPLO,
        entorno={"python": "3.12.14", "pip": "25.0.1", "zlib": "1.2.11"},
    )

    assert manifiesto["handler"] == "app.lambda_handler.handler"
    assert manifiesto["sha256"] == sha256_de(destino)
    assert manifiesto["plataforma"] == "linux/amd64"
    assert manifiesto["imagen"]["digest"].startswith("sha256:")
    assert manifiesto["entorno"]["python"] == "3.12.14"
    assert manifiesto["lock"]["sha256"]
    assert manifiesto["lock"]["distribuciones"] == 3
    assert manifiesto["medida"]["bytes_comprimidos"] == destino.stat().st_size
    assert len(manifiesto["archivos"]) == len(entradas)
    assert manifiesto["archivos"][0]["ruta"] == sorted(e.ruta for e in entradas)[0]
    assert manifiesto["archivos"][0]["sha256"]


def test_el_manifiesto_es_deterministico(tmp_path: Path) -> None:
    """H2 depende de esto: sin reloj ni rutas locales dentro del manifiesto.

    Las dos construcciones viven en directorios distintos pero producen el
    **mismo nombre de artefacto**, igual que hace el flujo real: `construir`
    siempre escribe `NOMBRE_DEL_ARTEFACTO`, y lo que cambia entre `A` y `B` es
    unicamente el directorio de salida.
    """
    manifiestos = []
    for nombre in ("A", "B"):
        raiz = _arbol_valido(tmp_path / nombre / "arbol")
        destino = tmp_path / nombre / NOMBRE_DEL_ARTEFACTO
        entradas = recolectar_entradas(raiz)
        escribir_zip(entradas, destino)
        manifiestos.append(
            construir_manifiesto(
                entradas=entradas,
                artefacto=destino,
                medida=medir(entradas, destino),
                distribuciones=distribuciones_del_lock(LOCK_DE_EJEMPLO),
                lock=LOCK_DE_EJEMPLO,
                entorno={"python": "3.12.14", "pip": "25.0.1", "zlib": "1.2.11"},
            )
        )

    assert manifiestos[0] == manifiestos[1]


def test_el_checksum_y_el_manifiesto_no_viajan_dentro_del_zip(tmp_path: Path) -> None:
    """Evita el artefacto autorreferencial: la metadata vive fuera del ZIP."""
    raiz = _arbol_valido(tmp_path / "arbol")
    destino = tmp_path / "a.zip"
    entradas = recolectar_entradas(raiz)
    escribir_zip(entradas, destino)
    (tmp_path / "manifiesto.json").write_text("{}", encoding="utf-8")
    (tmp_path / "a.zip.sha256").write_text(f"{sha256_de(destino)}  a.zip\n", encoding="utf-8")

    with zipfile.ZipFile(destino) as archivo:
        nombres = archivo.namelist()

    assert nombres == sorted(entrada.ruta for entrada in entradas)
    assert not [nombre for nombre in nombres if "manifiesto" in nombre or ".sha256" in nombre]
